version: '3.8'

services:

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"
    env_file:
      - .env.client

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8081:8081"
    env_file:
      - .env.server
