// protoのバージョンの宣言

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.26.1
// source: moderator.proto

// packageの宣言

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 型の定義
type HistoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Card string `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *HistoriesRequest) Reset() {
	*x = HistoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moderator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoriesRequest) ProtoMessage() {}

func (x *HistoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoriesRequest.ProtoReflect.Descriptor instead.
func (*HistoriesRequest) Descriptor() ([]byte, []int) {
	return file_moderator_proto_rawDescGZIP(), []int{0}
}

func (x *HistoriesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoriesRequest) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

type HistoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Histories []*History `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
}

func (x *HistoriesResponse) Reset() {
	*x = HistoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moderator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoriesResponse) ProtoMessage() {}

func (x *HistoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoriesResponse.ProtoReflect.Descriptor instead.
func (*HistoriesResponse) Descriptor() ([]byte, []int) {
	return file_moderator_proto_rawDescGZIP(), []int{1}
}

func (x *HistoriesResponse) GetHistories() []*History {
	if x != nil {
		return x.Histories
	}
	return nil
}

type Detail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In  string `protobuf:"bytes,1,opt,name=In,proto3" json:"In,omitempty"`
	Out string `protobuf:"bytes,2,opt,name=Out,proto3" json:"Out,omitempty"`
}

func (x *Detail) Reset() {
	*x = Detail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moderator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_moderator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_moderator_proto_rawDescGZIP(), []int{2}
}

func (x *Detail) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *Detail) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

type History struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DataType string  `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"`
	Category string  `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Date     string  `protobuf:"bytes,4,opt,name=Date,proto3" json:"Date,omitempty"`
	Value    int32   `protobuf:"varint,5,opt,name=Value,proto3" json:"Value,omitempty"`
	Detail   *Detail `protobuf:"bytes,6,opt,name=Detail,proto3" json:"Detail,omitempty"`
}

func (x *History) Reset() {
	*x = History{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moderator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_moderator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_moderator_proto_rawDescGZIP(), []int{3}
}

func (x *History) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *History) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *History) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *History) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *History) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *History) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

var File_moderator_proto protoreflect.FileDescriptor

var file_moderator_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6d, 0x79, 0x61, 0x70, 0x70, 0x22, 0x36, 0x0a, 0x10, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64,
	0x22, 0x41, 0x0a, 0x11, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x79, 0x61, 0x70, 0x70,
	0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x09, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x4f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4f, 0x75, 0x74, 0x22,
	0xa2, 0x01, 0x0a, 0x07, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25, 0x0a,
	0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x6d, 0x79, 0x61, 0x70, 0x70, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x32, 0x55, 0x0a, 0x10, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x6d, 0x79, 0x61, 0x70, 0x70,
	0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x79, 0x61, 0x70, 0x70, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x70,
	0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_moderator_proto_rawDescOnce sync.Once
	file_moderator_proto_rawDescData = file_moderator_proto_rawDesc
)

func file_moderator_proto_rawDescGZIP() []byte {
	file_moderator_proto_rawDescOnce.Do(func() {
		file_moderator_proto_rawDescData = protoimpl.X.CompressGZIP(file_moderator_proto_rawDescData)
	})
	return file_moderator_proto_rawDescData
}

var file_moderator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_moderator_proto_goTypes = []interface{}{
	(*HistoriesRequest)(nil),  // 0: myapp.HistoriesRequest
	(*HistoriesResponse)(nil), // 1: myapp.HistoriesResponse
	(*Detail)(nil),            // 2: myapp.Detail
	(*History)(nil),           // 3: myapp.History
}
var file_moderator_proto_depIdxs = []int32{
	3, // 0: myapp.HistoriesResponse.histories:type_name -> myapp.History
	2, // 1: myapp.History.Detail:type_name -> myapp.Detail
	0, // 2: myapp.HistoriesService.GetHistories:input_type -> myapp.HistoriesRequest
	1, // 3: myapp.HistoriesService.GetHistories:output_type -> myapp.HistoriesResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_moderator_proto_init() }
func file_moderator_proto_init() {
	if File_moderator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_moderator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moderator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moderator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Detail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moderator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*History); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_moderator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moderator_proto_goTypes,
		DependencyIndexes: file_moderator_proto_depIdxs,
		MessageInfos:      file_moderator_proto_msgTypes,
	}.Build()
	File_moderator_proto = out.File
	file_moderator_proto_rawDesc = nil
	file_moderator_proto_goTypes = nil
	file_moderator_proto_depIdxs = nil
}
